gui:
  scrollHeight: 20
  scrollPastBottom: false
  scrollOffMargin: 10
  sidePanelWidth: 0.2
  showListFooter: false
  showBottomLine: false
  showPanelJumps: false
  nerdFontsVersion: "3"
  commitHashLength: 4
  showDivergenceFromBaseBranch: arrowAndNumber
  border: single
  theme:
    # catppuccin-mocha
    inactiveBorderColor:
      - "#6c7086"
    selectedLineBgColor:
      - "#2a2b3c"
git:
  paging:
    pager: delta --dark --paging=never

    # --display=side-by-side-show-both
    # externalDiffCommand: difft --color=always --context=2 --syntax-highlight=off --tab-width=2 --display=inline
keybinding:
  universal:
    copyToClipboard: "y"
    undo: u
    redo: U
quitOnTopLevelReturn: true
notARepository: quit
promptToReturnFromSubprocess: false
