gui:
  scrollHeight: 16
  scrollPastBottom: false
  scrollOffMargin: 10
  sidePanelWidth: 0.16
  showListFooter: false
  showBottomLine: false
  nerdFontsVersion: "3"
  commitHashLength: 4
  showDivergenceFromBaseBranch: arrowAndNumber
  border: single

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
quitOnTopLevelReturn: true
notARepository: quit
promptToReturnFromSubprocess: false
keybinding:
  universal:
    prevBlock-alt: K
    nextBlock-alt: J
