gui:
  scrollHeight: 16
  scrollPastBottom: false
  scrollOffMargin: 10
  sidePanelWidth: 0.2
  showListFooter: false
  showBottomLine: false
  nerdFontsVersion: "3"
  commitHashLength: 4
  showDivergenceFromBaseBranch: arrowAndNumber
  border: single
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
keybinding:
  universal:
    copyToClipboard: "y"
    undo: u
    redo: U
quitOnTopLevelReturn: true
notARepository: quit
promptToReturnFromSubprocess: false
