gui:
  scrollHeight: 8
  scrollPastBottom: false
  scrollOffMargin: 10
  sidePanelWidth: 0.2
  # expandFocusedSidePanel: true
  showListFooter: false
  showBottomLine: false
  nerdFontsVersion: "3"
  commitHashLength: 0
  showDivergenceFromBaseBranch: arrowAndNumber
  border: single

git:
  paging:
    pager: delta --paging=never
  commit:
    autoWrapCommitMessage: false

quitOnTopLevelReturn: true
notARepository: quit
keybinding:
  universal:
    quit: <esc>
    prevBlock-alt: K
    nextBlock-alt: J
