# [env]
# TERM = "xterm-256color"

[window]
dynamic_padding = true
startup_mode = "Maximized"
dynamic_title = false
option_as_alt = "Both"

[font]
# normal = { family = "ZedMono Nerd Font" }
normal = { family = "MesloLGS Nerd Font" }
size = 16.0

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Beam"
vi_mode_style.shape = "Block"

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  # vi mode
  { key = "Space", mods = "Control", action = "ToggleViMode" },
  { key = "q", action = "ToggleViMode", mode = "Vi" },
  { key = "q", mods = "Control", action = "ToggleBlockSelection", mode = "Vi" },

  # vim
  # https://stackoverflow.com/questions/16359878/how-to-map-shift-enter
  { key = "Return", mods = "Shift", chars = "\u001B[13;2u", mode = "~Search" },
  { key = "Return", mods = "Control", chars = "\u001B[13;5u" },

  # csi keys
  # https://old.reddit.com/r/neovim/comments/mbj8m5/how_to_setup_ctrlshiftkey_mappings_in_neovim_and/
  # https://www.leonerd.org.uk/hacks/fixterms/
  # https://undelete.pullpush.io/r/neovim/comments/vguomm/how_can_i_map_tab_but_keep_the_default_action_for/
  # https://old.reddit.com/r/neovim/comments/vfqseq/enable_special_keyboard_combinations_in_alacritty/
  # https://www.google.com/search?q=alacritty-extended-keys+github
  # https://www.youtube.com/watch?v=-M7iQKTvTaQ
  # https://github.com/s1n7ax/alacritty-extended-keys
  { key = "i", mods = "Control", chars = "\u001b[105;5u" },
  { key = "C", mods = "Control|Shift", chars = "\u001b[67;5u" },
]

# https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/alacritty/NvimDark.toml
# Colors (NvimDark)
[colors.cursor]
cursor = '#9b9ea4'
# text = '#e0e2ea'

[colors.vi_mode_cursor]
cursor = '#fce094'

[colors.normal]
black = '#07080d'
blue = '#a6dbff'
cyan = '#8cf8f7'
green = '#b3f6c0'
magenta = '#ffcaff'
red = '#ffc0b9'
white = '#eef1f8'
yellow = '#fce094'

[colors.primary]
background = '#14161b'
foreground = '#e0e2ea'

[colors.selection]
background = '#4f5258'
text = '#e0e2ea'
