# [env]
# TERM = "xterm-256color"

[window]
dynamic_padding = true
# decorations = "None"
startup_mode = "Maximized"
dynamic_title = false
option_as_alt = "Both"

[scrolling]
multiplier = 1

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 18.0

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Beam"
vi_mode_style.shape = "Block"

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    # alacritty
    # { key = "Tab", mods = "Control", action = "SelectNextTab" },
    # { key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },

    # vi mode https://alacritty.org/config-alacritty-bindings.html
    { key = "Space", mods = "Control", action = "ToggleViMode" },
    { key = "q", action = "ToggleViMode", mode = "Vi" },
    { key = "q", mods = "Control", action = "ToggleBlockSelection", mode = "Vi" },
    # { key = "v", mods = "Control|Shift", action = "ToggleViMode" },
    # { key = "a", mods = "Command", action = "ToggleViMode" },

    # vim
    # https://stackoverflow.com/questions/16359878/how-to-map-shift-enter
    { key = "Return", mods = "Shift", chars = "\u001B[13;2u", mode = "~Search" },
    { key = "Return", mods = "Control", chars = "\u001B[13;5u" },
    # { key = "Space", mods = "Control", chars = "\u0000" },

    # https://old.reddit.com/r/neovim/comments/mbj8m5/how_to_setup_ctrlshiftkey_mappings_in_neovim_and/
    # https://www.leonerd.org.uk/hacks/fixterms/
    # { key = "H", mods = "Control|Shift", chars = "\u001b[72;5u" },
    # { key = "J", mods = "Control|Shift", chars = "\u001b[74;5u" },
    # { key = "K", mods = "Control|Shift", chars = "\u001b[75;5u" },
    # { key = "L", mods = "Control|Shift", chars = "\u001b[77;5u" },
    { key = "G", mods = "Control|Shift", chars = "\u001b[71;5u" },
    { key = "C", mods = "Control|Shift", chars = "\u001b[67;5u" },

    # zellij
    # control-a control-n
    { key = "Tab", mods = "Control", chars = "\u0001\u000e" },
    # control-a control-p
    { key = "Tab", mods = "Control|Shift", chars = "\u0001\u0010" },
]

# bamboo https://github.com/ribru17/bamboo.nvim/blob/master/extras/alacritty/bamboo.toml
[colors]
cursor = { cursor = "#3a4238" }
vi_mode_cursor = { cursor = "#bb9631" }
selection = { text = "CellForeground", background = "CellForeground" }

# [colors.search]
# matches = { foreground = "#d8dee9", background = "#5b7a88" }
# focused_match = { foreground = "#d8dee9", background = "#40505d" }

# Default colors
[colors.primary]
background = '#fafae0'
foreground = '#3a4238'

# Normal colors
[colors.normal]
black = '#c7c7af'
red = '#c72a3c'
green = '#27850b'
yellow = '#bb9631'
blue = '#1745d5'
magenta = '#8a4adf'
cyan = '#188a9e'
white = '#3a4238'

# Bright colors
[colors.bright]
black = '#a1a7a0'
red = '#c72a3c'
green = '#27850b'
yellow = '#bb9631'
blue = '#1745d5'
magenta = '#8a4adf'
cyan = '#188a9e'
white = '#252623'
