# [env]
# TERM = "xterm-256color"

[window]
dynamic_padding = true
decorations = "transparent"
startup_mode = "Maximized"
dynamic_title = false
option_as_alt = "Both"

[font]
# normal = { family = "ZedMono Nerd Font" }
normal = { family = "MesloLGS Nerd Font" }
size = 16.0

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Beam"
vi_mode_style.shape = "Block"

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [
  # vi mode
  { key = "Space", mods = "Control", action = "ToggleViMode" },
  { key = "q", action = "ToggleViMode", mode = "Vi" },
  { key = "q", mods = "Control", action = "ToggleBlockSelection", mode = "Vi" },

  # vim
  # https://stackoverflow.com/questions/16359878/how-to-map-shift-enter
  { key = "Return", mods = "Shift", chars = "\u001B[13;2u", mode = "~Search" },
  { key = "Return", mods = "Control", chars = "\u001B[13;5u" },

  # csi keys
  # https://old.reddit.com/r/neovim/comments/mbj8m5/how_to_setup_ctrlshiftkey_mappings_in_neovim_and/
  # https://www.leonerd.org.uk/hacks/fixterms/
  # https://undelete.pullpush.io/r/neovim/comments/vguomm/how_can_i_map_tab_but_keep_the_default_action_for/
  # https://old.reddit.com/r/neovim/comments/vfqseq/enable_special_keyboard_combinations_in_alacritty/
  # https://www.google.com/search?q=alacritty-extended-keys+github
  # https://www.youtube.com/watch?v=-M7iQKTvTaQ
  # https://github.com/s1n7ax/alacritty-extended-keys
  { key = "i", mods = "Control", chars = "\u001b[105;5u" },
  { key = "C", mods = "Control|Shift", chars = "\u001b[67;5u" },
]

# https://github.com/catppuccin/alacritty/blob/main/catppuccin-mocha.toml
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
# cursor = "#f5e0dc"
cursor = "#ffffff"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"
# cursor = '#fce094'

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"
