# https://alacritty.org/config-alacritty.html
# https://github.com/alacritty/alacritty/issues/6999#issuecomment-1903342590# man 5 alacritty
[env]
TERM = "xterm-256color"

[window]
padding = { x = 0, y = 0 }
# dynamic_padding = true
decorations = "full"
# opacity = 0.90
# blur = true
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
normal = { family = "FiraCode Nerd Font" }
size = 18.0

# [colors]
# transparent_background_colors = true

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    { key = "Enter", mods = "Shift", chars = "ci\"" },
    { key = "Enter", mods = "Control", chars = "ci'" },
]

# https://github.com/slugbyte/lackluster.nvim/blob/main/extra/alacritty/alacritty.toml[colors.primary]
[colors.primary]
background = '#101010'

[colors.normal]
black = '#080808'
red = '#D70000'
green = '#789978'
yellow = '#ffAA88'
blue = '#7788AA'
magenta = '#D7007D'
cyan = '#5D6D6D'
white = '#cfecf3'
