# [env]
# TERM = "xterm-256color"

[window]
dynamic_padding = true
# decorations = "None"
startup_mode = "Maximized"
dynamic_title = false
option_as_alt = "Both"

[scrolling]
multiplier = 1

[font]
# normal = { family = "Hack Nerd Font" }
normal = { family = "MesloLGS Nerd Font" }
size = 18.0

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Beam"
vi_mode_style.shape = "Block"

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  # vi mode
  { key = "Space", mods = "Control", action = "ToggleViMode" },
  { key = "q", action = "ToggleViMode", mode = "Vi" },
  { key = "q", mods = "Control", action = "ToggleBlockSelection", mode = "Vi" },

  # vim
  # https://stackoverflow.com/questions/16359878/how-to-map-shift-enter
  { key = "Return", mods = "Shift", chars = "\u001B[13;2u", mode = "~Search" },
  { key = "Return", mods = "Control", chars = "\u001B[13;5u" },
  # { key = "Space", mods = "Control", chars = "\u0000" },

  # csi keys
  # https://old.reddit.com/r/neovim/comments/mbj8m5/how_to_setup_ctrlshiftkey_mappings_in_neovim_and/
  # https://www.leonerd.org.uk/hacks/fixterms/
  # https://undelete.pullpush.io/r/neovim/comments/vguomm/how_can_i_map_tab_but_keep_the_default_action_for/
  # https://old.reddit.com/r/neovim/comments/vfqseq/enable_special_keyboard_combinations_in_alacritty/
  # https://www.google.com/search?q=alacritty-extended-keys+github
  # https://www.youtube.com/watch?v=-M7iQKTvTaQ
  # https://github.com/s1n7ax/alacritty-extended-keys
  # control
  { key = "h", mods = "Control", chars = "\u001b[104;5u" },
  { key = "i", mods = "Control", chars = "\u001b[105;5u" },
  { key = "j", mods = "Control", chars = "\u001b[106;5u" },
  { key = "m", mods = "Control", chars = "\u001b[109;5u" },
  # control+shift
  { key = "C", mods = "Control|Shift", chars = "\u001b[67;5u" },
  { key = "G", mods = "Control|Shift", chars = "\u001b[71;5u" },

  # zellij
  # control-a control-n
  { key = "Tab", mods = "Control", chars = "\u0001\u000e" },
  # control-a control-p
  { key = "Tab", mods = "Control|Shift", chars = "\u0001\u0010" },
]

# https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/alacritty/NvimDark.toml
# Colors (NvimDark)
# [colors.bright]
# black = '#4f5258'
# blue = '#a6dbff'
# cyan = '#8cf8f7'
# green = '#b3f6c0'
# magenta = '#ffcaff'
# red = '#ffc0b9'
# white = '#eef1f8'
# yellow = '#fce094'
# [colors.cursor]
# cursor = '#9b9ea4'
# # text = '#e0e2ea'
# [colors.vi_mode_cursor]
# cursor = '#fce094'
# [colors.normal]
# black = '#07080d'
# blue = '#a6dbff'
# cyan = '#8cf8f7'
# green = '#b3f6c0'
# magenta = '#ffcaff'
# red = '#ffc0b9'
# white = '#eef1f8'
# yellow = '#fce094'
# [colors.primary]
# background = '#14161b'
# foreground = '#e0e2ea'
# [colors.selection]
# background = '#4f5258'
# text = '#e0e2ea'


# nord https://github.com/alacritty/alacritty-theme/blob/master/themes/nord.toml
[colors]
cursor = { cursor = "#D8DEE9" }
vi_mode_cursor = { cursor = "#EBCB8B" }
selection = { text = "CellForeground", background = "CellForeground" }
# [colors.search]
# matches = { foreground = "#d8dee9", background = "#5b7a88" }
# focused_match = { foreground = "#d8dee9", background = "#40505d" }
[colors.primary]
background = '#2E3440'
foreground = '#D8DEE9'
[colors.normal]
black = '#3B4252'
red = '#BF616A'
green = '#A3BE8C'
yellow = '#EBCB8B'
blue = '#81A1C1'
magenta = '#B48EAD'
cyan = '#88C0D0'
white = '#E5E9F0'
[colors.bright]
black = '#4C566A'
red = '#BF616A'
green = '#A3BE8C'
yellow = '#EBCB8B'
blue = '#81A1C1'
magenta = '#B48EAD'
cyan = '#8FBCBB'
white = '#ECEFF4'
