# https://starship.rs/config/#prompt
"$schema" = 'https://starship.rs/config-schema.json'
# add_newline = false

[character]
error_symbol = "[✗](bold red)"

[cmd_duration]
min_time          = 2_000
show_milliseconds = true

[directory]
truncation_length = 8
truncate_to_repo  = false
style             = 'underline blue'

[git_branch]
always_show_remote = true

[hostname]
ssh_only = false
format   = '[$hostname]($style) '

[localip]
disabled = false

[time]
format   = '[$time]($style) '
style	   = 'dimmed white'
disabled = false
