# https://starship.rs/config/#prompt
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
palette     = "rose_pine"
format      = """
[░▒▓](foam)\
$directory\
$git_branch\
$git_status\
$golang\
$rust\
$python\
$time\
$character\
"""
right_format = """
$cmd_duration\
"""

[directory]
disabled          = false
truncation_length = 4
truncation_symbol = "…/"
truncate_to_repo  = false
style             = "fg:foam bg:pine"
format            = "[ $path ]($style)"

[git_branch]
disabled           = false
symbol             = ""
always_show_remote = true
style              = "bg:hl_high"
format             = '[[ $symbol $branch ](fg:foam bg:hl_high)]($style)'

[git_status]
disabled = false
style    = "bg:hl_high"
format   = '[[($all_status$ahead_behind )](fg:foam bg:hl_high)]($style)'

[golang]
disabled = false
symbol   = ""
style    = "bg:hl_mid"
format   = '[[ $symbol ($version) ](fg:foam bg:hl_mid)]($style)'
[rust]
disabled = false
symbol   = ""
style    = "bg:hl_mid"
format   = '[[ $symbol ($version) ](fg:foam bg:hl_mid)]($style)'
[python]
disabled = false
symbol   = ""
style    = "bg:hl_mid"
format   = '[[ $symbol ($version) ](fg:foam bg:hl_mid)]($style)'

[time]
disabled = false
style    = "bg:hl_low"
format   = '[[ $time ](fg:subtle bg:hl_low)]($style)'

[character]
disabled       = false
# success_symbol = '[❯](bold foam)'
# https://www.nerdfonts.com/cheat-sheet
success_symbol = '[](bold foam)'
# 󱍿
# 󱣀
error_symbol   = "[✗](bold love)"
format         = ' $symbol '

[cmd_duration]
disabled          = false
min_time          = 2_000
show_milliseconds = true

# https://rosepinetheme.com/palette/ingredients/#rose-pine
[palettes.rose_pine]
base    = "#191724"
surface = "#1f1d2e"
overlay = "#26233a"
muted   = "#6e6a86"
subtle  = "#908caa"
text    = "#e0def4"
love    = "#eb6f92"
gold    = "#f6c177"
rose    = "#ebbcba"
pine    = "#31748f"
foam    = "#9ccfd8"
iris    = "#c4a7e7"
hl_low  = "#21202e"
hl_mid  = "#403d52"
hl_high = "#524f67"
