# https://starship.rs/config/#prompt
"$schema" = 'https://starship.rs/config-schema.json'

# add_newline = false
format = """
$directory\
$git_branch\
$rust\
$python\
$character\
"""
right_format = """
$cmd_duration\
"""

[directory]
disabled = false
truncation_length = 8
truncation_symbol = "…/"
truncate_to_repo = false
format = "[$path ](white)"

[git_branch]
disabled = false
symbol = ""
always_show_remote = true
format = '[$symbol $branch ](green)'

[rust]
disabled = false
symbol = ""
format = '[$symbol ($version )](yellow)'

[python]
disabled = false
symbol = ""
format = '[$symbol ($version )(\($virtualenv\) )](yellow)'

[character]
disabled = false
success_symbol = '[❯](green)'
error_symbol = "[✗](red)"
format = '$symbol '

[cmd_duration]
disabled = false
min_time = 2_000
show_milliseconds = true
format = '[$duration](yellow)'
