return {
  -- {
  --   'OXY2DEV/markview.nvim',
  --   ft = 'markdown',
  --   config = function()
  --     require('markview').setup({})
  --   end,
  -- },
  -- {
  --   'MeanderingProgrammer/markdown.nvim',
  --   ft = 'markdown',
  --   dependencies = {
  --     'echasnovski/mini.icons',
  --   },
  --   config = function()
  --     local markdown = require('render-markdown')
  --     markdown.setup({
  --       enabled = false,
  --       -- not working in visual for some reason
  --       -- render_modes = { 'n', 'c', 'x' },
  --       anti_conceal = {
  --         enabled = false,
  --       },
  --     })
  --
  --     vim.keymap.set(
  --       'n',
  --       '<leader>tM',
  --       markdown.toggle,
  --       { desc = 'Toggle Markdown' }
  --     )
  --   end,
  -- },
  -- {
  --   'ravibrock/spellwarn.nvim',
  --   config = true,
  --   enabled = false,
  -- },
}
