# https://alacritty.org/config-alacritty.html
# https://github.com/alacritty/alacritty/issues/6999
# man 5 alacritty

#[shell]

[env]
TERM = "xterm-256color"

[window]
decorations   = "None"
opacity       = 0.85
startup_mode  = "Maximized"
dynamic_title = false
option_as_alt = "Both"

[scrolling]
multiplier = 1

[font]
normal = { family = "FiraCode Nerd Font"}
size   = 15.0

[colors]
transparent_background_colors     = true
draw_bold_text_with_bright_colors = true

[bell]

[selection]
semantic_escape_chars = ",│‘|:\"' ()[]{}<>"
save_to_clipboard     = true

[cursor]
style          = { shape = "Beam", blinking = "Always" }
blink_interval = 500
blink_timeout  = 0
thickness      = 0.1

[terminal]

[mouse]

[hints]

[keyboard]

[debug]
