# https://alacritty.org/config-alacritty.html
# https://github.com/alacritty/alacritty/issues/6999#issuecomment-1903342590# man 5 alacritty
import = [
    "~/.config/alacritty/themes/themes/nightfox.toml"
]

[env]
# TERM = "xterm-256color"

[window]
decorations   = "None"
opacity       = 0.90
startup_mode  = "Maximized"
option_as_alt = "Both"

[scrolling]
multiplier = 1

[font]
normal = { family = "FiraCode Nerd Font"}
size   = 16.0
offset = { x = 0, y = -4 }

[colors]
transparent_background_colors     = true
draw_bold_text_with_bright_colors = true

[bell]

[selection]
save_to_clipboard = true

[cursor]

[terminal]

[mouse]

[hints]

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "L", mods = "Control|Shift", chars = "l" },
]

[debug]
