# https://alacritty.org/config-alacritty.html
# https://github.com/alacritty/alacritty/issues/6999#issuecomment-1903342590# man 5 alacritty

[env]
TERM = "xterm-256color"

[window]
decorations   = "None"
opacity       = 0.85
startup_mode  = "Maximized"
option_as_alt = "Both"

[scrolling]
multiplier = 1

[font]
normal = { family = "FiraCode Nerd Font"}
size   = 16.0

[colors]
transparent_background_colors     = true
draw_bold_text_with_bright_colors = true

[bell]

[selection]
save_to_clipboard = true

[cursor]

[terminal]

[mouse]

[hints]

[keyboard]

[debug]
