# https://docs.helix-editor.com/keymap.html
# https://github.com/helix-editor/helix/blob/master/helix-term/src/commands.rs
# https://github.com/LGUG2Z/helix-vim/blob/master/config.toml
# https://github.com/helix-editor/helix/wiki/Migrating-from-Vim
theme = "nightfox"
# theme = "ayu_mirage"
# theme = "tokyonight_storm"

[editor]
line-number            = "relative"
cursorline             = true
cursorcolumn           = true
completion-trigger-len = 1
true-color             = true
undercurl              = true
bufferline             = "always"
color-modes            = true

[editor.statusline]
left        = ["mode", "register", "spacer", "version-control", "file-name", "file-encoding", "read-only-indicator"]
# center      = ["selections", "primary-selection-length"]
right       = ["spinner", "diagnostics", "position", "position-percentage", "spacer", "separator", "total-line-numbers"]
mode.normal = "[N]"
mode.insert = "[I]"
mode.select = "[S]"

[editor.lsp]
display-messages    = true
# display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
# select = "underline"

[editor.file-picker]
hidden = false

[editor.search]
wrap-around = false

[editor.whitespace.render]
space   = "all"
tab     = "all"
newline = "none"

[editor.indent-guides]
render      = true
skip-levels = 1

[editor.gutters.line-numbers]
min-width = 1

[editor.soft-wrap]
enable            = true
max-wrap          = 0
max-indent-retain = 0
wrap-indicator    = ""


[keys.normal]
# better defaults
esc     = ["collapse_selection", "keep_primary_selection"]
i       = ["insert_mode",        "collapse_selection"]
a       = ["append_mode",        "collapse_selection"]
"tab"   = "goto_next_buffer"
"S-tab" = "goto_previous_buffer"
"*"     = ["move_prev_word_start", "move_next_word_end", "search_selection"]

# shared with normal/select
S           = "surround_add"
X           = "extend_line_above"
"ret"       = ["open_below", "normal_mode"]
"backspace" = "delete_char_backward"
A-j         = ["yank", "paste_after",  "collapse_selection"]
A-k         = ["yank", "paste_before", "collapse_selection"]
"{"         = "goto_prev_paragraph"
"}"         = "goto_next_paragraph"
# personal preference
q   = "select_textobject_inner"
Q   = "select_textobject_around"
";" = "flip_selections"
"," = "remove_primary_selection"
A-c = "copy_selection_on_prev_line"
# movement
J = ["move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "align_view_center"]
K = ["move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "align_view_center"]
L = "extend_to_line_end"
H = "extend_to_line_start"
G = "goto_file_end"

# recentering
n   = ["search_next",    "align_view_center"]
N   = ["search_prev",    "align_view_center"]
U   = ["redo",           "align_view_center"]
C-u = ["half_page_up",   "align_view_center"]
C-d = ["half_page_down", "align_view_center"]
C-b = ["page_up",        "align_view_center"]
C-f = ["page_down",      "align_view_center"]
C-i = ["jump_forward",   "align_view_center"]
C-o = ["jump_backward",  "align_view_center"]

# window navigation
C-h       = "jump_view_left"
C-j       = "jump_view_down"
C-k       = "jump_view_up"
C-l       = "jump_view_right"
C-4       = "vsplit" # C-\
C-7       = "hsplit" # C-minus
"A-\\"    = "vsplit_new"
"A-minus" = "hsplit_new"

# leader https://docs.helix-editor.com/keymap.html#space-mode
[keys.normal.space]
w       = ":write"
q       = ":quit"
x       = ":buffer-close"
F       = "file_picker_in_current_buffer_directory"
"space" = "goto_last_modified_file"
c       = ":lsp-workspace-command"
r       = "replace_selections_with_clipboard"
R       = ":config-reload"
# unbinds
k = "no_op"
h = "no_op"
a = "no_op"
g = "no_op"

# zellij run
# y = ":sh zellij run --floating -- yadm status"
l = ":sh zellij run --floating --close-on-exit -- lazygit"
L = ":sh zellij run --close-on-exit --in-place -- yadm enter lazygit"
# hacked explorer
# e = ":sh zellij run --direction 'Right' -- $HOME/.config/eza/eza-wrapper.sh -lAot -T -L 3"
# e = ":sh zellij run --direction 'Right' -- tree -L 3"

# goto mode https://docs.helix-editor.com/keymap.html#goto-mode
[keys.normal.g]
k = "hover"
a = "code_action"
s = "select_references_to_symbol_under_cursor"
R = "rename_symbol"
h = "signature_help"
f = "goto_file_vsplit"
# unbinds
e = "no_op"
l = "no_op"
j = "no_op"
n = "no_op"
p = "no_op"
t = "no_op"
c = "no_op"
b = "no_op"
m = "no_op"


[keys.select]
# esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
esc = ["collapse_selection", "normal_mode"]

# shared with normal/select
S           = "surround_add"
X           = "extend_line_above"
"ret"       = ["open_below", "normal_mode"]
"backspace" = "delete_char_backward"
A-j         = ["yank", "paste_after",  "collapse_selection"]
A-k         = ["yank", "paste_before", "collapse_selection"]
"{"         = "goto_prev_paragraph"
"}"         = "goto_next_paragraph"
# personal preference
q   = "select_textobject_inner"
Q   = "select_textobject_around"
";" = "flip_selections"
"," = "remove_primary_selection"
A-c = "copy_selection_on_prev_line"
# movement
J = ["extend_line_down", "extend_line_down", "extend_line_down", "extend_line_down", "extend_line_down", "extend_line_down"]
K = ["extend_line_up", "extend_line_up", "extend_line_up", "extend_line_up", "extend_line_up", "extend_line_up"]
L = "extend_to_line_end"
H = "extend_to_line_start"
G = "goto_file_end"


[keys.insert]
esc = ["collapse_selection", "normal_mode"]
C-c = "toggle_comments"
C-l = "move_char_right"
C-h = "move_char_left"
C-k = "move_line_up"
C-j = "move_line_down"
