theme = "gruvbox_dark_hard"

[editor]
line-number  = "relative"
scroll-lines = 1
# cursorline   = true
# cursorcolumn = true
bufferline   = "always"
auto-format  = false
rulers       = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.gutters.line-numbers]
min-width = 1

[editor.indent-guides]
render = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.insert]
up    = "no_op"
down  = "no_op"
left  = "no_op"
right = "no_op"
esc   = ["collapse_selection", "normal_mode"]

[keys.normal]
esc   = ["collapse_selection", "keep_primary_selection"]
C-r   = ":config-reload"
C-s   = ":w"
C-o   = ":config-open"
D     = ["ensure_selections_forward", "extend_to_line_end"]
X     = "extend_line_above"
0     = "goto_line_start"
"$"   = "goto_line_end"
up    = "no_op"
down  = "no_op"
left  = "no_op"
right = "no_op"
"{"   = "goto_prev_paragraph"
"}"   = "goto_next_paragraph"
C-h   = "goto_previous_buffer"
C-l   = "goto_next_buffer"

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

