theme = "gruvbox"

[editor]
scroll-lines = 1
cursorline   = true
cursorcolumn = true
bufferline   = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.gutters.line-numbers]
min-width = 1

[editor.indent-guides]
render = true
