theme = "gruvbox_dark_hard"

[editor]
scroll-lines = 1
# cursorline   = true
# cursorcolumn = true
bufferline   = "always"
auto-format  = false
rulers       = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.gutters.line-numbers]
min-width = 1

[editor.indent-guides]
render = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
esc   = ["collapse_selection", "keep_primary_selection"]
"C-r" = [":config-reload"]
"C-s" = [":w"]
"C-o" = [":config-open"]
"G"   = ["goto_last_line"]
"D"   = ["ensure_selections_forward", "extend_to_line_end"]
"="   = [":format"]
