# https://docs.helix-editor.com/keymap.html
# https://github.com/LGUG2Z/helix-vim/blob/master/config.toml
# https://github.com/helix-editor/helix/wiki/Migrating-from-Vim
theme = "nightfox"
# theme = "ayu_mirage"

[editor]
line-number  = "relative"
cursorline   = true
cursorcolumn = true
bufferline   = "always"
auto-format  = true
# rulers       = [80]

[editor.statusline]
left        = ["mode", "version-control", "file-name", "read-only-indicator", "file-modification-indicator"]
center      = ["selections"]
right       = ["diagnostics", "position-percentage", "total-line-numbers", "spinner"]
mode.normal = "[N]"
mode.insert = "[I]"
mode.select = "[S]"

[editor.lsp]
display-messages    = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace]
render = "all"

[editor.indent-guides]
render      = true
skip-levels = 1

[editor.gutters.line-numbers]
min-width = 1

[editor.search]
wrap-around = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

# movement
J   = ["move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down"]
K   = ["move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up"]
L   = "goto_line_end"
H   = "goto_line_start"
G   = "goto_last_line"
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
# C-k = "select_prev_sibling"
# C-h = "shrink_selection"
# C-l = "expand_selection"
# C-j = "select_next_sibling"

# selection/changes
s           = ["move_prev_word_start", "move_next_word_end"]
# S           = "expand_selection"
V           = ["extend_to_line_end"]
A-v         = ["extend_to_line_start"]
D           = "kill_to_line_end"
X           = "extend_line_above"
A-c         = "copy_selection_on_prev_line"
"ret"       = ["open_below", "normal_mode"]
"backspace" = "delete_char_backward"

# indent
"tab"   = "indent"
"S-tab" = "unindent"

# search
n   = ["search_next", "align_view_center"]
N   = ["search_prev", "align_view_center"]
C-d = ["half_page_down", "align_view_center"]
C-u = ["half_page_up", "align_view_center"]

# buffer navigation
"[" = { "[" = "goto_previous_buffer" }
"]" = { "]" = "goto_next_buffer" }
C-n = [":buffer-next"]
C-p = [":buffer-previous"]

# unbinds
# g     = { "n" = "no_op", "p" = "no_op"}

# [keys.normal.ctrl]
C-r = ":config-reload"
C-s = ":w"
# window navigation
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-4 = "vsplit" # C-\
C-7 = "hsplit" # C-minus

# leader
[keys.normal.space]
q = ":quit"
d = ":buffer-close"

# zellij run
[keys.normal."+"]
b = ":run-shell-command zellij run -f -- yadm diff"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]
# esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
C-f = "move_char_right"
C-b = "move_char_left"
C-c = "toggle_comments"

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
