# https://docs.helix-editor.com/keymap.html
# https://github.com/helix-editor/helix/blob/master/helix-term/src/commands.rs
# https://github.com/LGUG2Z/helix-vim/blob/master/config.toml
# https://github.com/helix-editor/helix/wiki/Migrating-from-Vim
theme = "nightfox"
# theme = "ayu_mirage"
# theme = "tokyonight_storm"

[editor]
line-number  = "relative"
cursorline   = true
cursorcolumn = true
bufferline   = "always"
auto-format  = true
color-modes  = true

[editor.statusline]
left        = ["mode", "spacer", "version-control", "file-name", "file-encoding", "read-only-indicator"]
# center      = ["selections", "primary-selection-length"]
right       = ["spinner", "diagnostics", "position", "position-percentage", "spacer", "separator", "total-line-numbers"]
mode.normal = "[N]"
mode.insert = "[I]"
mode.select = "[S]"

[editor.lsp]
display-messages    = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render      = true
skip-levels = 1

[editor.gutters.line-numbers]
min-width = 1

[editor.soft-wrap]
enable = true

[editor.search]
wrap-around = false







[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# unbinds
C-w = "no_op"

# overrides/vim habits
C-v   = "copy_selection_on_next_line"
C-b   = "remove_primary_selection"
A-v   = "copy_selection_on_prev_line"
V     = "extend_to_line_end"
C-f   = "search"
"ret" = ["open_below", "normal_mode"]
S     = ["move_prev_word_start", "move_next_word_end"]
# C   = ["extend_to_line_end", "yank", "delete_selection", "insert_mode"]
# D   = ["extend_to_line_end", "yank", "delete_selection"]
# i           = ["insert_mode", "collapse_selection"]
# a           = ["append_mode", "collapse_selection"]

# movement
J = ["move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down"]
K = ["move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up"]
L = "goto_line_end"
H = "goto_line_start"
G = "goto_last_line"

# changes
"tab"       = "indent"
"S-tab"     = "unindent"
A-j         = ["yank", "paste_after",  "collapse_selection"]
A-k         = ["yank", "paste_before", "collapse_selection"]
# inserts
"backspace" = "delete_char_backward"

# selection manipulation
";" = "flip_selections"
X   = "extend_line_above"
"{" = ["goto_prev_paragraph", "align_view_center"]
"}" = ["goto_next_paragraph", "align_view_center"]

# recentering
n   = ["search_next",    "align_view_center"]
N   = ["search_prev",    "align_view_center"]
C-d = ["half_page_down", "align_view_center"]
C-u = ["half_page_up",   "align_view_center"]
u   = ["undo",           "align_view_center"]
U   = ["redo",           "align_view_center"]

# buffer navigation
"[" = { "[" = "goto_previous_buffer" }
"]" = { "]" = "goto_next_buffer" }

# [keys.normal.ctrl]
C-r = ":config-reload"
C-s = ":w"
# window navigation
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-4 = "vsplit" # C-\
C-7 = "hsplit" # C-minus

# leader
[keys.normal.space]
q = ":quit"
d = ":buffer-close"
# zellij run
[keys.normal.space.z]
y = ":run-shell-command zellij run -f -- yadm status"
g = ":run-shell-command zellij run -f -- lazygit"
# unbinds
[keys.normal.space.w]
"C-w"   = "no_op"
"C-s"   = "no_op"
"C-v"   = "no_op"
"C-t"   = "no_op"
"C-q"   = "no_op"
"C-o"   = "no_op"
"C-h"   = "no_op"
"C-j"   = "no_op"
"C-k"   = "no_op"
"C-l"   = "no_op"
"left"  = "no_op"
"right" = "no_op"
"up"    = "no_op"
"down"  = "no_op"
"h"     = "no_op"
"j"     = "no_op"
"k"     = "no_op"
"l"     = "no_op"

# goto mode
[keys.normal.g]
# unbinds
e = "no_op"
h = "no_op"
l = "no_op"
j = "no_op"
k = "no_op"
n = "no_op"
p = "no_op"

[keys.select]
esc = ["collapse_selection", "normal_mode"]
# esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
# ";" = ["collapse_selection", "normal_mode"]
# a   = ["append_mode", "collapse_selection"]
# i   = ["insert_mode", "collapse_selection"]

# movement
L = "goto_line_end"
H = "goto_line_start"
G = "goto_last_line"

# selection manipulation
";" = "flip_selections"
X   = "extend_line_above"
"{" = ["goto_prev_paragraph", "align_view_center"]
"}" = ["goto_next_paragraph", "align_view_center"]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]
# esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
C-c = "toggle_comments"
C-l = "move_char_right"
C-h = "move_char_left"
C-k = "move_line_up"
C-j = "move_line_down"
