theme = "gruvbox_material_dark_hard"

[editor]
line-number  = "relative"
# mouse        = false
scroll-lines = 1
# cursorline   = true
# cursorcolumn = true
bufferline   = "always"
auto-format  = false
rulers       = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.gutters.line-numbers]
min-width = 1

[editor.indent-guides]
render = true

[editor.search]
wrap-around = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.insert]
up    = "no_op"
down  = "no_op"
left  = "no_op"
right = "no_op"
esc   = ["collapse_selection", "normal_mode"]

[keys.normal]
esc   = ["collapse_selection", "keep_primary_selection"]
C-r   = ":config-reload"
C-s   = ":w"
D     = "kill_to_line_end"
X     = "extend_line_above"
up    = "no_op"
down  = "no_op"
left  = "no_op"
right = "no_op"
A-c = "copy_selection_on_prev_line"
# paragraph navigation
"{"   = "goto_prev_paragraph"
"}"   = "goto_next_paragraph"
# buffer navigation
"["   = { "[" = "goto_previous_buffer" }
"]"   = { "]" = "goto_next_buffer" }
# move lines
C-j   = ["extend_to_line_bounds", "delete_selection", "paste_after"] 
C-k   = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
# better jumplist
C-i   = "jump_backward"
C-o   = "jump_forward"

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
# paragraph navigation
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

