# [language-server.gpt]
# command = "bun"
# args = ["run", "/usr/local/bin/helix-gpt", "--handler", "copilot"]
# https://github.com/leona/helix-gpt/issues/49
[language-server.gpt]
command = "deno"
args    = ["run", "--allow-env", "--allow-net", "/Users/jshu/git/helix-gpt/src/app.ts", "--handler", "copilot"]

[[language]]
name             = "python"
language-servers = ["pyright", "gpt"]

[[language]]
name             = "rust"
language-servers = ["rust-analyzer", "gpt"]

[[language]]
name             = "toml"
language-servers = ["gpt"]

[[language]]
name             = "kdl"
language-servers = ["gpt"]

[[language]]
name             = "markdown"
language-servers = ["gpt"]
